ls1intum/Apollon_standalone

packages/webapp/src/main/services/editor-options/editor-options-reducer.ts, packages/webapp/src/main/services/editor-options/editor-options-types.ts, packages/webapp/tsconfig.json, tsconfig.json
This PR handles integration of changes in https://github.com/ls1intum/Apollon/pull/204 .
Apollon now provides output in lib/es5 and lib/es6.
We want to also upgrade our typescript to produce es2020 output.
I adjusted two required paths to consume from apollon/lib/es6.
I upgraded the root and webapp tsconfig to produce es2020 output
These changes should be tested in conjunction with my Apollon PR (https://github.com/ls1intum/Apollon/pull/204).
Steps:
1. Inside Apollon repository:
1.1. checkout the `enhancement/create_additional_es5_output ` in apollon.
1.2. `rm -rf node_modules && yarn install && yarn prepare`
1.3. `yarn link`
2. Inside Apollon_standalone
2.1. checkout the `enhancement/include_es6_apollon `  branch
2.2. ` yarn install && yarn link "@ls1intum/apollon" && yarn start`
The …
=> enhancement: include new lib/es6 output of apollon. 

packages/shared/package.json, packages/webapp/package.json, yarn.lock
This PR fixes the issue that the current version of Apollon standalone is having while building the project.
Issue Number: https://github.com/ls1intum/Apollon_standalone/issues/27
Update Apollon package to fix the build failing issue. 
1. Clone the Repo
2. Execute `yarn install`
3. Execute `yarn build:local`
4. It should now be working as expected.
=> Update Apollon package

packages/webapp/src/main/styles.css, packages/webapp/src/main/themings.json
This PR fixes a couple of dark mode issues in Standalone.
- Warning text in firefox is now visible in dark mode.
- Close icon of toaster is now visible in darkmode.
Issue Number: https://github.com/ls1intum/Apollon_standalone/issues/40
- Goto [test server](https://test1.apollon.ase.in.tum.de/) in Firefox browser.
- Set the application to dark mode.
- Observe that the warning text is now visible.
- Share the diagram and observe that the close icon of the toaster is now visible in dark mode, as illustrated in screenshots.
=> ``Development``: Fix for darkmode issues

packages/webapp/src/main/components/application-bar/menues/file-menu.tsx, packages/webapp/src/main/services/export/export-repository.ts, packages/webapp/src/main/services/export/export-types.ts, packages/webapp/src/main/services/export/png/export-png-epics.ts
This PR allows users to export their diagram in PNG with white as well as transparent background.
1. Goto [test server](https://test1.apollon.ase.in.tum.de/).
2. Add couple of elements in the canvas
3. Export the diagram with transparent background by clicking on File > Export > As PNG (Transparent Background)
4. Export the diagram with white background by clicking on File > Export > As PNG (White Background)
5. Verify the exported diagrams are exported correctly (with selected backgrounds type).
=> `Development`: Export PNGs with Transparent/White Background

packages/webapp/src/main/components/application-bar/menues/theme-switcher-menu.tsx, packages/webapp/src/main/components/modals/create-diagram-modal/create-diagram-modal.tsx, packages/webapp/src/main/styles.css
This PR removes the experimental tag from the theme switcher popup and the beta tag from Flowchart.
- Goto [test server](https://test1.apollon.ase.in.tum.de/)
- Click on File >New from the menu
- Observe that the beta tag is removed from Flowchart
- Hover on theme switcher icon
- Observe that the Experimental tag is removed from the popup
=> `Development`: Remove experimental and beta tag 

packages/webapp/src/main/components/modals/share-modal/share-modal.tsx
Previously users were allowed to share empty diagrams and were notified with an "import error" message only after accessing the shared URL.
The error message was generic and did not make sense while sharing an empty diagram.
This PR restricts users from sharing empty diagrams in the first place. 
- Deploy branch `enhancement/disable-sharing-empty-diagram` to the test server
- Goto [test server](https://test1.apollon.ase.in.tum.de/) once its deployed
- Try sharing the empty diagram 
- Observe that the sharing fails and the user is notified with an error message.
=> `Development`: Restrict users from sharing empty diagram

packages/server/src/main/services/conversion-service/conversion-service.ts
We now await till the next render cycle of Apollon and the redux store is initialized to avoid these errors.
This PR only makes the Apollon Conversion Service run again. It does not solve the issue with incorrectly rendering Apollon diagrams from Artemis.
=> Fix Apollon Conversion Service fails with error because of uninitialised redux store

Dockerfile, packages/server/package.json, packages/server/src/main/services/conversion-service/conversion-service.ts
This PR attempts to solve the issues with the conversion service exiting with an error code when attempting to export a Apollon diagram as SVG.
The issue seems to be the initialization of the package JSDOM. The package used for initilization previously (jsdom-global) is no longer maintained and has last been updated in 2017. The replacement package "global-jsdom" seems to resolve this issue.
I additionally updated the node version of the Docker image as the global-jsdom package expects a minimum version of node 18.
=> Resolve issues with the conversion service exiting unexpectedly

package-lock.json, packages/shared/package.json, packages/webapp/package.json, packages/webapp/src/main/components/apollon-editor-component/apollon-editor-component.tsx, packages/webapp/src/main/styles.css
This PR adds support for Apollon 3.3.1.
To get the sidebar to overflow and scroll correctly, a few CSS adaptions have to be made.
=> Add support for Apollon 3.3.1

packages/webapp/src/main/components/apollon-editor-component/apollon-editor-component.tsx, packages/webapp/src/main/utils/patch-verifier.ts
With current implementation of realtime collaboration, there was an issue of self-stuttering. This PR suppresses such stuttering by signing issued change operations and locally discarding broadcast changes that a client optimistically anticipates will be overwritten.
Current implementation of realtime collaboration relies on strongly idempotent changes being broadcast by clients, temporally sorted by the server and re-broadcast to all clients (including the client who issued the change initially).
- Changes are strongly idempotent: a client applying a change would get the same result regardless of whether they have already, at some point in the past, applied the change or not, or how many times.
- This yields eventual consistency, as each client in the end applies the same sequence of …
=> suppress self-stuttering

package-lock.json, packages/server/package.json, packages/server/src/main/services/diagram-storage/diagram-file-storage-service.ts
Currently, the file storage for diagrams acts eagerly, i.e. the diagram file is written to anytime a client makes a change to the diagram. When changes become frequent, this results in corrupted files (as changes overlap each other), and subsequently result in the server process crashing.
With this change, writing to diagram files is paced to avoid this issue. Non-existent files are still saved eagerly, but already existing files will have a debounce before being saved (currently `500ms`, configurable). In scenarios where the diagram is being updated rapidly (e.g. multiple peers, continuous sync, etc) this can cause long waits before saving a diagram, which increases the risk of data loss in case of unforeseen crashes. To mitigate this issue, I've ensured that when there are rapid …
=> More stable persistence

packages/server/src/main/services/collaboration-service/collaboration-service.ts, packages/server/src/main/services/diagram-storage/diagram-file-storage-service.ts, packages/server/src/main/services/diagram-storage/diagram-storage-service.ts
Previously, diagram saves (for example, during realtime collaboration) would follow these steps:
1. The server would receive a change from a client
2. The server would load the diagram
3. The server would apply the changes
4. The server would save the diagram and broadcast the changes
Since updating diagrams was not atomic, there was a potential for clashes while updating a diagram: for example an update could be initiated by another client while the server is between steps 2 and 4, resulting in corrupted stored data.
This PR changes the process to enable atomic updates, resolving this issue:
1. The server will receive a change from a client
2. The server atomically updates the diagram
3. The server broadcasts the change
The `DiagramStorageService` interface is updated with two additional …
=> add support for atomic saves

packages/webapp/src/main/components/modals/create-diagram-modal/create-diagram-modal.tsx
This PR adds support for tracking when a new diagram is created and which type of diagram is created to PostHog.
=> Track diagram creation including diagram type

packages/webapp/src/main/index.html
To promote the newly released iOS app for Apollon, this PR adds a smart app banner to index.html of the web app.
=> Add Smart App Banner to promote newly released iOS app

README.md, package-lock.json, packages/server/package.json, packages/server/src/main/resources/diagram-resource.ts, packages/server/src/main/services/collaboration-service/collaboration-service.ts, packages/server/src/main/services/diagram-storage/diagram-file-storage-service.ts, packages/server/src/main/services/diagram-storage/diagram-redis-storage-service.ts, packages/server/src/main/services/diagram-storage/diagram-storage-rate-limiter.ts, packages/server/src/main/services/diagram-storage/diagram-storage-service.ts, packages/server/src/main/services/diagram-storage/index.ts, packages/server/src/main/services/diagram-storage/redis-patch.ts
This PR adds support for using Redis as the storage service of Apollon Standalone (instead of file-based storage). After merging this PR, Apollon Standalone will look for `APOLLON_REDIS_URL` environment variable, and if present, switch to Redis as its storage backend. See [these docs](https://www.npmjs.com/package/redis#usage) for further info on the format of the Redis URL. If the environment variable is not present, Apollon Standalone will fallback into using the filesystem based storage it was already using.
The main benefit of using Redis as the storage backend is stability of high-frequency writes. Specifically in context of realtime collaboration, it can happen that diagrams are constantly updated, which, using a file based storage, means potentially colliding write operations …
=> add redis storage integration

Dockerfile, Dockerfile.redis, README.md, package-lock.json, packages/server/package.json, packages/server/src/main/services/diagram-storage/diagram-redis-storage-service.ts, packages/server/src/main/services/diagram-storage/index.ts, packages/server/webpack/webpack.config.js, packages/shared/package.json, packages/webapp/package.json
This PR will add a Dockerfile and instructions that enable deploying (locally or to a server) using Docker while using Redis as storage backend. To achieve this, I had to fix the following small issues as well:
- The build configuration was buggy (regardless of Docker), omitting essential packages from the server bundle which would not allow WebSockets to work.
- The default Dockerfile is out of date. I think in a follow-up PR the Dockerfile can be re-written and perhaps the two Dockerfiles can be merged, so connecting to Redis is solely controlled via environment variables passed to the container.
- Support for expiring shared diagrams stored on Redis was added. In the file-storage solution, a cron service was to be configured to ensure cleanup. For Redis, this can be achieved via a …
=> Support deployment with Redis using Docker

Dockerfile.redis, README.md, docker-compose.yml
This PR adds a docker compose file for deploying to production using Docker, and using Redis as a storage service.
The Docker file for utilising Redis is also updated to accept a deployment URL as an argument during build time, since this information is injected in packed client code during build time.
This PR also updates the documentation (on README) on how to deploy using Docker and Redis. Basically, `docker compose up -d` should do the trick, though for a production configuring the environment would be highly recommended as well.
=> Docker compose deployment

.github/workflows/build-and-push-shared.yml, .github/workflows/deploy-dev.yml, .github/workflows/deploy-docker-compose-shared.yml, docker-compose.prod.yml, docker-compose.yml
Makes the workflow more robust and already generalizes it a bit for extracting it to ls1intum/.github
=> Improve deploy workflow

packages/server/src/main/resources/diagram-resource.ts
When returning a diagram, headers are set in the response so that the GitHub's CDN cache is invalidated. This ensures that diagram embeddings are not cached and therefore always up to date.
Idea from https://stackoverflow.com/a/27893930
=> Invalidate GitHub cache so that embeddings are not cached

packages/webapp/src/main/components/modals/share-modal/share-modal.tsx
This PR removes the 'Edit copy' link that was present when embedding a diagram
=> Remove edit copy link

packages/server/src/main/routes.ts
Fixing PDF export
Routing in server routes was not finding the correct endpoint for diagrams/pdf
Changing order makes API call to correct function
https://github.com/user-attachments/assets/07992b02-2411-49e5-aa97-f0f32a394d49
=> Fix pdf export
